### ISSUE TITLE
VT_TIMEPROG is no DTTM

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#250]
Hi,

I suggest giving VT_TIMEPROG its own Datatype.
VT_TIMEPROG is definitely not date and time.  (... DT_DTTM,    // date and time ...)
https://github.com/fredlcore/bsb_lan/blob/a6e54115a863e54f0ec86c58dbd6e7859992ab58/BSB_lan_defs.h#L604

I know that this is a small breaking change for users of the JSON API, but this is for me more the correction of a bug.

Here we can also solve #246 together with this issue.
Rename DT_WDAY -> DT_TPROG, so that the DT_ENUMs after this are consistent. (enum and enum string mapping)
Remove VT_WEEKDAY

Change DT_DTTM to DT_TPROG in line: https://github.com/fredlcore/bsb_lan/blob/a6e54115a863e54f0ec86c58dbd6e7859992ab58/BSB_lan_defs.h#L604

In bsbJS I got it working to parse all payloads from the DT Enums, and this makes also fully sense because the DataType defines the payload structure. The only missing point is the VT_TIMEPROG because this is in my eyes not correct with DT_DTTM. See picture

![image](https://user-images.githubusercontent.com/1100969/103473623-fc696500-4d9a-11eb-89dd-347b66434aad.png)

**Comment by dukess** [comment]
It is a good idea.

**Comment by fredlcore** [comment]
For breaking changes for external modules, I would want to first compile a list of external modules so that we can at least notifiy module maintainers of this change. Once this is done, I would be okay with this change.

**Comment by dukess** [comment]
Changes for this issue in separate branch: https://github.com/dukess/bsb_lan/commit/c1befd254eaf563a5a4d183f6e5c76216dfa9372

**Comment by dukess** [comment]
@fredlcore Do you have any news?

**Comment by fredlcore** [comment]
Neither regarding the list of module maintainers nor a decision whether we can get rid of VT_WEEKDAY since this may have to be used for the newly found way to set day of week (as well as time) for PPS. Stay tuned...

**Comment by dukess** [comment]
Modified changes (VT_WEEKDAY needed again)
https://github.com/dukess/bsb_lan/commit/c47c9dfcad413f54400dd411e593b144e88d36ca

**Comment by konne** [comment]
@dukess with this decision I think you can add the DT_TMPR just as a new element in the end without any breaking change, right?

**Comment by fredlcore** [comment]
That should be fine of course. But where do we need DT_TMPR in the first case?

**Comment by dukess** [comment]
@konne DT_WDAY is never used so here no difference: add new type or replace exist.
@fredlcore for JSON generation/parsing.

**Comment by hacki11** [comment]
+1 for making a difference here. 
No breaking change for ioBroker users due to write is not implemented for datatype 5 & 6 and read out is only a string for them.

**Comment by fredlcore** [comment]
Ok, I hope this does it: https://github.com/fredlcore/BSB-LAN/commit/c7708026ba0a5670cf71af13bc59e712c57836f3

**Comment by hacki11** [comment]
Is there a difference between `dataType` and `dataType_name` ? Is this a 1:1 mapping?

**Comment by hacki11** [comment]
Is anyone having a PPS system and can send me a /JQ Parameter output example with datatype PPS_Time?

I think there is only one:
{0x2D790028,  CAT_PPS,              VT_PPS_TIME,      15040, STR15040, 0,                    NULL,         DEFAULT_FLAG, DEV_ALL}, // Heater time

**Comment by fredlcore** [comment]
Not sure where you are referring to these variables, but in general:
There is `dt_types_t` which is an ENUM encoding for the different data types such as hour:minute, string, plain value etc.
There is `vt_type_t` which is an ENUM encoding for the different value types such as gradient, integral, unsigned integer etc.
There is `dt_types_text` which holds the textual representation of `dt_types_t` for use in the JSON API because `dt_types_t` is just an ordered index which could change if positions in the ENUM change (which they shouldn't).

Does this answer your question?
As for the PPS output, you can also query this yourself because PPS values are not actively queried on the bus but rather evaluated broadcasts. So you can just set the bus to PPS by setting `/P2,1` and then do `/JQ=15040` and then switch back to BSB by doing a `/P0,66,0`.

But if it's just 15040 you need, here's the output:
```
{
  "15040": {
    "name": "Uhrzeit",
    "dataType_name": "PPS_TIME",
    "dataType_family": "DWHM",
    "error": 0,
    "value": "15:26:11",
    "desc": "",
    "dataType": 8,
    "readonly": 0,
    "unit": ""
  }
}
```

**Comment by hacki11** [comment]
Yes, that answers my question, thanks. I have added the pps example to api doc
