### ISSUE TITLE
WRITE Only for Parameter / Commands

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#254]
Hi,

can you add an WRITEONLY flag, to the flags, so that commands like:

https://github.com/fredlcore/bsb_lan/blob/59cfff50d31b22ec0584ff139d4bc394eeb7ab17/BSB_lan_defs.h#L6970

can be written, even if a read of the parameter would be not successful.

Maybe this is also a solution for TWW Push,...

bye

**Comment by fredlcore** [comment]
Flag FL_WONLY added.
