### ISSUE TITLE
Please clarify JL & JW

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#268]
Hi,

if I read a config via JL and get for example an element with the JSON Key 3 and Id 6
```
  "3": {
    "id": "6",
```
What is important for write. The correct ID (6) or the correct key (3)

bye
Konrad

**Comment by dukess** [comment]
"3" is a displaying order. You can ignore it.
"6" is real ID.

**Comment by konne** [comment]
@dukess: so if I understand it right I have to send back:

````json
{
  "ANYKEY": {
    "id": "6",                  
    "value": "new Value to Write" 
  }
}
```

correct?

**Comment by dukess** [comment]
No. Syntax is same as for /JS because same parser used:
{{"parameter": 6, "value": "new Value to Write"}, {"parameter": 22, "value": "something new"}}

**Comment by hacki11** [comment]
Is this command ne or already present in 1.x?
What does this really do? I found 'Reads the list of configuration created with /JL and adjusts the settings' but what configuration can be set? What is different to /JS?

**Comment by dukess** [comment]
No. It is new feature.
/JL and /JW used for configuring BSB-LAN not heater/cooler etc.
Jürgen Schmid <notifications@github.com> 8 января 2021 г. 20:33:19 написал:

**Comment by hacki11** [comment]
Is it GET or POST?
Can you give me real-life examples for both in terms of request and response?

**Comment by dukess** [comment]
POST. /JS, /JW support POST only.
/JQ, /JC, /JR, can be queried with GET and POST.

/JL, /JI, /JV queried without parameters.

/JL. Payload can be named as combination /JC and /JQ. It contain possible values for ENUMs and current values

{
  "0": {
    "id": "0",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_USEEEPROM_TEXT",
    "value": "150",
    "possibleValues": [
      { "enumValue": "105", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "150", "desc": "MENU_TEXT_ON" }
      ]
    },
  "3": {
    "id": "6",
    "type": "1",
    "format": "3",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_BUSTYPE_TEXT",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "BSB" },
      { "enumValue": "1", "desc": "LPB" },
      { "enumValue": "2", "desc": "PPS" }
      ]
    },
  "4": {
    "id": "7",
    "type": "1",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_OWN_BSBADDR_TEXT",
    "value": "66"
    },
  "5": {
    "id": "8",
    "type": "1",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_OWN_LPBADDR_TEXT",
    "value": "66"
    },
  "6": {
    "id": "9",
    "type": "1",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_DEST_LPBADDR_TEXT",
    "value": "0"
    },
  "7": {
    "id": "10",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_PPS_WRITE_TEXT",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "8": {
    "id": "43",
    "type": "2",
    "format": "3",
    "category": "CAT_GENERAL_TEXT",
    "name": "STR15062_TEXT",
    "value": "83",
    "possibleValues": [
      { "enumValue": "82", "desc": "ENUM15062_52_TEXT" },
      { "enumValue": "83", "desc": "ENUM15062_53_TEXT" }
      ]
    },
  "9": {
    "id": "17",
    "type": "5",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "MENU_TEXT_MAC",
    "value": "00:80:41:19:69:90"
    },
  "10": {
    "id": "18",
    "type": "1",
    "format": "2",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_DHCP_TEXT",
    "value": "1",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "11": {
    "id": "19",
    "type": "6",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_IPADDRESS_TEXT",
    "value": "192.168.67.88"
    },
  "12": {
    "id": "20",
    "type": "6",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_MASK_TEXT",
    "value": "255.255.255.0"
    },
  "13": {
    "id": "21",
    "type": "6",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_GATEWAY_TEXT",
    "value": "192.168.67.1"
    },
  "14": {
    "id": "22",
    "type": "6",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_DNS_TEXT",
    "value": "192.168.67.1"
    },
  "15": {
    "id": "23",
    "type": "2",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_WWWPORT_TEXT",
    "value": "80"
    },
  "16": {
    "id": "24",
    "type": "6",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_TRUSTEDIPADDRESS_TEXT",
    "value": "0.0.0.0"
    },
  "17": {
    "id": "25",
    "type": "6",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_TRUSTEDIPADDRESS_TEXT",
    "value": "0.0.0.0"
    },
  "18": {
    "id": "47",
    "type": "4",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_WIFI_SSID_TEXT",
    "value": "YourWiFiNetwork"
    },
  "19": {
    "id": "48",
    "type": "4",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_MQTT_PASSWORD_TEXT",
    "value": "YourWiFiPassword"
    },
  "20": {
    "id": "11",
    "type": "1",
    "format": "3",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_LOGTELEGRAM_TEXT",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_LAT" },
      { "enumValue": "2", "desc": "MENU_TEXT_BUT (MENU_TEXT_OFF)" },
      { "enumValue": "3", "desc": "MENU_TEXT_BUT" },
      { "enumValue": "4", "desc": "MENU_TEXT_LBO (MENU_TEXT_OFF)" },
      { "enumValue": "5", "desc": "MENU_TEXT_LBO" },
      { "enumValue": "6", "desc": "MENU_TEXT_UBT (MENU_TEXT_OFF)" },
      { "enumValue": "7", "desc": "MENU_TEXT_UBT" }
      ]
    },
  "21": {
    "id": "12",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "MENU_TEXT_AVT",
    "value": "1",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "22": {
    "id": "13",
    "type": "7",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_AVERAGESLIST_TEXT",
    "value": "8700,8326"
    },
  "23": {
    "id": "14",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_LOGCURRVALUES_TEXT",
    "value": "1",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "24": {
    "id": "15",
    "type": "3",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_LOGCURRINTERVAL_TEXT",
    "value": "3600"
    },
  "25": {
    "id": "16",
    "type": "7",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_CURRVALUESLIST_TEXT",
    "value": "8700,8314,8830,8740"
    },
  "26": {
    "id": "26",
    "type": "4",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_PASSKEY_TEXT",
    "value": ""
    },
  "27": {
    "id": "27",
    "type": "4",
    "format": "1",
    "category": "CAT_IPV4_TEXT",
    "name": "CF_BASICAUTH_TEXT",
    "value": ""
    },
  "29": {
    "id": "29",
    "type": "1",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_ONEWIREBUS_TEXT",
    "value": "3"
    },
  "30": {
    "id": "30",
    "type": "9",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_DHTBUS_TEXT",
    "value": "2,3"
    },
  "31": {
    "id": "31",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_IPWE_TEXT",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "32": {
    "id": "32",
    "type": "7",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_IPWEVALUESLIST_TEXT",
    "value": "8700,8743,8314,8750,8830,8740,8741,8326,8337,8703,8704"
    },
  "33": {
    "id": "33",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_MAX_TEXT",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "34": {
    "id": "34",
    "type": "6",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_MAX_IPADDRESS_TEXT",
    "value": "192.168.178.5"
    },
  "35": {
    "id": "3",
    "type": "8",
    "format": "1",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_MAX_DEVICES_TEXT",
    "value": "KEQ0502326,KEQ0505080"
    },
  "38": {
    "id": "35",
    "type": "1",
    "format": "3",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_WRITEMODE_TEXT",
    "value": "1",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "ENUM_WRITE_ENG_TEXT" },
      { "enumValue": "2", "desc": "ENUM_WRITE_OEM_TEXT" }
      ]
    },
  "39": {
    "id": "36",
    "type": "1",
    "format": "3",
    "category": "CAT_GENERAL_TEXT",
    "name": "CF_DEBUG_TEXT",
    "value": "2",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "ENUM_DEBUG_SERIAL_TEXT" },
      { "enumValue": "2", "desc": "ENUM_DEBUG_TELNET_TEXT" }
      ]
    },
  "40": {
    "id": "45",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "MENU_TEXT_VBL",
    "value": "1",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "41": {
    "id": "44",
    "type": "1",
    "format": "2",
    "category": "CAT_GENERAL_TEXT",
    "name": "MENU_TEXT_MMD",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    },
  "42": {
    "id": "37",
    "type": "1",
    "format": "3",
    "category": "CAT_MQTT_TEXT",
    "name": "CF_MQTT_TEXT",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "ENUM_MQTT_PLAIN_TEXT" },
      { "enumValue": "2", "desc": "ENUM_MQTT_JSON_TEXT" },
      { "enumValue": "3", "desc": "ENUM_MQTT_JSON2_TEXT" }
      ]
    },
  "43": {
    "id": "38",
    "type": "6",
    "format": "1",
    "category": "CAT_MQTT_TEXT",
    "name": "CF_MQTT_IPADDRESS_TEXT",
    "value": "192.168.66.1"
    },
  "44": {
    "id": "39",
    "type": "4",
    "format": "1",
    "category": "CAT_MQTT_TEXT",
    "name": "CF_MQTT_USERNAME_TEXT",
    "value": ""
    },
  "45": {
    "id": "40",
    "type": "4",
    "format": "1",
    "category": "CAT_MQTT_TEXT",
    "name": "CF_MQTT_PASSWORD_TEXT",
    "value": ""
    },
  "46": {
    "id": "41",
    "type": "4",
    "format": "1",
    "category": "CAT_MQTT_TEXT",
    "name": "CF_MQTT_TOPIC_TEXT",
    "value": "BSB-LAN"
    },
  "47": {
    "id": "42",
    "type": "4",
    "format": "1",
    "category": "CAT_MQTT_TEXT",
    "name": "CF_MQTT_TOPIC_TEXT",
    "value": "MyHeater"
    },
  "48": {
    "id": "46",
    "type": "1",
    "format": "2",
    "category": "CAT_MQTT_TEXT",
    "name": "MENU_TEXT_NVA",
    "value": "0",
    "possibleValues": [
      { "enumValue": "0", "desc": "MENU_TEXT_OFF" },
      { "enumValue": "1", "desc": "MENU_TEXT_ON" }
      ]
    }

}



/JW. Query. Data must be send with POST. Write new config values. field "parameter" is field "id" from /JL.

{
{"parameter": 0, "value": "150"},
{"parameter": 6, "value": "0"},
{"parameter": 7, "value": "66"},
{"parameter": 8, "value": "66"},
{"parameter": 9, "value": "0"},
{"parameter": 10, "value": "0"},
{"parameter": 43, "value": "83"},
{"parameter": 17, "value": "00:80:41:19:69:90"},
{"parameter": 18, "value": "1"},
{"parameter": 19, "value": "192.168.67.88"},
{"parameter": 20, "value": "255.255.255.0"},
{"parameter": 21, "value": "192.168.67.1"},
{"parameter": 22, "value": "192.168.67.1"},
{"parameter": 23, "value": "80"},
{"parameter": 24, "value": "0.0.0.0"},
{"parameter": 25, "value": "0.0.0.0"},
{"parameter": 47, "value": "YourWiFiNetwork"},
{"parameter": 48, "value": "YourWiFiPassword"},
{"parameter": 11, "value": "0"},
{"parameter": 12, "value": "1"},
{"parameter": 13, "value": "8700,8326"},
{"parameter": 14, "value": "1"},
{"parameter": 15, "value": "3600"},
{"parameter": 16, "value": "8700,8314,8830,8740"},
{"parameter": 26, "value": ""},
{"parameter": 27, "value": ""},
{"parameter": 29, "value": "3"},
{"parameter": 30, "value": "2,3"},
{"parameter": 31, "value": "0"},
{"parameter": 32, "value": "8700,8743,8314,8750,8830,8740,8741,8326,8337,8703,8704"},
{"parameter": 33, "value": "0"},
{"parameter": 34, "value": "192.168.178.5"},
{"parameter": 3, "value": "KEQ0502326,KEQ0505080"},
{"parameter": 35, "value": "1"},
{"parameter": 36, "value": "2"},
{"parameter": 45, "value": "1"},
{"parameter": 44, "value": "0"},
{"parameter": 37, "value": "0"},
{"parameter": 38, "value": "192.168.66.1"},
{"parameter": 39, "value": ""},
{"parameter": 40, "value": ""},
{"parameter": 41, "value": "BSB-LAN"},
{"parameter": 42, "value": "MyHeater"},
{"parameter": 46, "value": "0"}
}

/JW Answer. Write status like /JS
{
  "0": {
    "status": 1
  },
  "6": {
    "status": 1
  },
  "7": {
    "status": 1
  },
  "8": {
    "status": 1
  },
  "9": {
    "status": 1
  },
  "10": {
    "status": 1
  },
  "43": {
    "status": 1
  },
  "17": {
    "status": 1
  },
  "18": {
    "status": 1
  },
  "19": {
    "status": 1
  },
  "20": {
    "status": 1
  },
  "21": {
    "status": 1
  },
  "22": {
    "status": 1
  },
  "23": {
    "status": 1
  },
  "24": {
    "status": 1
  },
  "25": {
    "status": 1
  },
  "47": {
    "status": 1
  },
  "48": {
    "status": 1
  },
  "11": {
    "status": 1
  },
  "12": {
    "status": 1
  },
  "13": {
    "status": 1
  },
  "14": {
    "status": 1
  },
  "15": {
    "status": 1
  },
  "16": {
    "status": 1
  },
  "26": {
    "status": 1
  },
  "27": {
    "status": 1
  },
  "29": {
    "status": 1
  },
  "30": {
    "status": 1
  },
  "31": {
    "status": 1
  },
  "32": {
    "status": 1
  },
  "33": {
    "status": 1
  },
  "34": {
    "status": 1
  },
  "3": {
    "status": 1
  },
  "35": {
    "status": 1
  },
  "36": {
    "status": 1
  },
  "45": {
    "status": 1
  },
  "44": {
    "status": 1
  },
  "37": {
    "status": 1
  },
  "38": {
    "status": 1
  },
  "39": {
    "status": 1
  },
  "40": {
    "status": 1
  },
  "41": {
    "status": 1
  },
  "42": {
    "status": 1
  },
  "46": {
    "status": 1
  }
}

**Comment by hacki11** [comment]
Thanks for the explanation!

Is this intentionally:
- Parameter in /JL as field "id" is of type _string_ and
- parameter in /JW Request as field "parameter" is of type _integer_
Shouldn't it be the same data type?

In 
```
{
            id: '0', 
            type: '1', 
            format: '2', 
            category: 'CAT_GENERAL_TEXT', 
            name: 'CF_USEEEPROM_TEXT', 
            value: '150', 
            possibleValues: [
              {
                enumValue: '105', 
                desc: 'MENU_TEXT_OFF'
              }, 
              {
                enumValue: '150', 
                desc: 'MENU_TEXT_ON'
              }
            ]
          },
```
Can you help me with /JL Response:
- type: Which types exists, what values do they have, really a string not an integer?
- format: Which formats exists, what values do they have, really a string not an integer?

Updated: https://app.swaggerhub.com/apis/hacki11/BSB-LAN/2.0#/general/getConfiguration
Thanks

**Comment by dukess** [comment]
> Shouldn't it be the same data type?

Of course, all mentioned fields must be numbers. Moreover i think to rename "id" to "parameter" while a little time has passed and this module is not used everywhere.

These two fields allow to build user interface:

> type: Which types exists, what values do they have, really a string not an integer?

0 -  CDT_VOID, // byte array (for internal using. Never sent through JSON)
1 -  CDT_BYTE, //unsigned byte. can be various format (text, switch, dropdown)
2 -  CDT_UINT16, //CPI_TEXT field with format for unsigned integer
3 -  CDT_UINT32, //CPI_TEXT field with format for unsigned long integer
4 -  CDT_STRING, //CPI_TEXT field
5 -  CDT_MAC, //CPI_TEXT field with format for MAC input/output
6 -  CDT_IPV4, //CPI_TEXT field with format for IPv4 input/output
7 -  CDT_PROGNRLIST, //CPI_TEXT field with format for programs list input/output
8 -  CDT_MAXDEVICELIST,//CPI_TEXT field with format for MAX! devices list input/output
9 -  CDT_DHTBUS //CPI_TEXT field with format for DHT bus

> format: Which formats exists, what values do they have, really a string not an integer?

Using for select HTML input type. 0 - none 1 - text field, 2 - switch, 3 - dropdown

**Comment by konne** [comment]
> Of course, all mentioned fields must be numbers. Moreover i think to rename "id" to "parameter" while a little time has passed and this module is not used everywhere.
@dukess: that would be great. The API is new and it make sense to make the changes now. I also agree with @hacki11 that consistent naming and datatypes are important. So I like your idea to rename id -> parameter

**Comment by hacki11** [comment]
I also recognised many hashmaps as responses. It is more common to use arrays and place the key as field inside the object. 
But openapi supports both, no real issue here

**Comment by konne** [comment]
@dukess  please can you here use also names instead of ids for the type.
If you ever has to change the "C" code the api is independent of that changes.
so type: "VOID" or type: "BYTE" ,....

thx

**Comment by hacki11** [comment]
That would be great, I then can automatically generate the enum type

**Comment by dukess** [comment]
@hacki11 
>I also recognised many hashmaps as responses. It is more common to use arrays and place the key as field inside the object.

Parser will be more complex, so i leave it for client side.

@konne To be honest i do not want do it right now because every text string consume space. It can be critical for Mega users. So i think do stable release first and then made improvements.

**Comment by hacki11** [comment]
I forgot one thing to ask. In /JW Response, the status field:
1 = OK
2 = NOT_FOUND
Is that correct?

**Comment by dukess** [comment]
Correct!

Jürgen Schmid <notifications@github.com> 9 января 2021 г. 13:53:46 написал:

**Comment by dukess** [comment]
@konne @hacki11 Note: /JK and /JC command can return HTTP code 304 "Not Modified" without payload if ETag will be same. As ETag BSB-LAN version is used.

**Comment by hacki11** [comment]
Is the E-Tag feature available with plain /JC /JK or also if the user gives parameters?

Then we would have 3 different responses with the same E-Tag, which will cause issues:
/JC
/JC=700
/JC=700,710
How is this implemented?

**Comment by dukess** [comment]
user parameters allowed.
BSB-LAN return same ETag for different queries.
By fact /JK=x /JC=x commands return static content which can be changed only after software upgrading. I.e ETag describe actual version.

**Comment by hacki11** [comment]
That means, the client has to determine if the content will be different or not (e.g. change parameters) prior the request? Imho that could have been solved by ETag taking the parameter keys into account.

**Comment by dukess** [comment]
Form Wiki:
In typical usage, when a URL is retrieved, the Web server will return the 
resource's current representation along with its corresponding ETag value, 
which is placed in an HTTP response header "ETag" field:

ETag: "686897696a7c876b7e"


The client may then decide to cache the representation, along with its 
ETag. Later, if the client wants to retrieve the same URL resource again, 
it will first determine whether the locally cached version of the URL has 
expired (through the Cache-Control and the Expire headers). If the URL has 
not expired, it will retrieve the locally cached resource. If it is 
determined that the URL has expired (is stale), the client will send a 
request to the server that includes its previously-saved copy of the ETag 
in the "If-None-Match" field.[2]

If-None-Match: "686897696a7c876b7e"


On this subsequent request, the server may now compare the client's ETag 
with the ETag for the current version of the resource. If the ETag values 
match, meaning that the resource has not changed, the server may send back 
a very short response with a HTTP 304 Not Modified status. The 304 status 
tells the client that its cached version is still good and that it should 
use that.

However, if the ETag values do not match, meaning the resource has likely 
changed, a full response including the resource's content is returned, just 
as if ETags were not being used. In this case, the client may decide to 
replace its previously cached version with the newly returned 
representation of the resource and the new ETag.
Jürgen Schmid <notifications@github.com> 12 января 2021 г. 14:12:50 написал:

**Comment by hacki11** [comment]
Thanks for the explanation, backed with caching makes sense for queries having everything in the request uri.

I assume the POST /JC call with the request body does not support etags, right? Because the cache does only use the request uri which would be the same for different requests.

**Comment by dukess** [comment]
I made fix for /JC & POST: ETag will be disabled for this case.

**Comment by fredlcore** [comment]
Can we consider this closed?

**Comment by hacki11** [comment]
From my side I'm fine!
