### ISSUE TITLE
http server hangs? 

### ISSUE THREAD

**Issue by iTobs** [fredlcore/BSB-LAN#350]
The BSB-LAN adapter no longer reacts to requests on port 80. Neither from the browser or via telnet. 
It sends values to mqtt. A ping also answers.
In the seriel monitor the arduino shows that it is working.
But i cannot access the website.
In the log i don't can see any abnormalities. 
The last working http-question was OK:
GET /K49 HTTP/1.1
Now i don't can see any http questions in the log. 

Restarting the serial monitor restarts the due. 
Now everything works fine.

Does anyone have any ideas about the cause?

**Comment by fredlcore** [comment]
Is it reproducible or just a one-time glitch?

**Comment by iTobs** [comment]
Some time ago, when the adapter was already hanging, I hadn't opened a serial monitor...
I will watch it.

**Comment by fredlcore** [comment]
Ok, closing for now, feel free to re-open when the problem persists...

**Comment by iTobs** [comment]
The error occurs because I cannot query the log via telnet and access bsb-lan via http at the same time.

**Comment by fredlcore** [comment]
You can change the debug output to serial and run the terminal either from the Arduino IDE or any other terminal program.
