### ISSUE TITLE
Logging of parameter 0 is not possible

### ISSUE THREAD

**Issue by fredlcore** [fredlcore/BSB-LAN#367]
While it may sound useless, I wanted to log parameter 0 for debugging purposes to have a timestamp from the heater. I found out that logging of parameter 0 is not possible: The field in the webinterface returns empty after saving. Setting it via `/L=60,0` returns a confirmation, but the parameter is still not logged. Do you have any idea why this is so, @dukess?

**Comment by dukess** [comment]
It's not working because arrays (ipwe, log, mqtt) filled with zeros and 
every element checking for non-zero value. You can try to use functions 1-3.
fredlcore ***@***.***> 16 апреля 2021 г. 1:23:49 написал:

**Comment by fredlcore** [comment]
Got it, thanks!
