### ISSUE TITLE
One wire sensor not working

### ISSUE THREAD

**Issue by Charodej** [fredlcore/BSB-LAN#368]
Hello,
Inn version 20210121102308 one wire sensor works correctly DS18B20 but in newer versions with the same HW and no change in SF, only update -> one wire sensor does not work. 
Only DHT22 sensors works in both versions - new and old.

**Comment by fredlcore** [comment]
Please post a log of what's going on when you query the sensor(s). @1coderookie, do you have DS18B20s running in your setup at the moment and a recent version of BSB-LAN? Do you encounter the same problem?

**Comment by 1coderookie** [comment]
@Charodej : Just for my information & my testing scenario: do you have more than one DS18B20 sensor or only one? Which system, Due or ESP32? Which pin(s) do you use for the OneWire(s)?
@fredlcore :  I'll try with a test-setup and the current version asap..

**Comment by fredlcore** [comment]
@1coderookie: Thanks!

**Comment by Charodej** [comment]
Using more DS18B20 on pin 7 with DS18B20 adapter on Arduino Due.

**Comment by 1coderookie** [comment]
Sorry, but I don't really understand what you mean by that.. :(
How many sensors and which kind of "DS18B20 adapter"? The one I show in the manual at the end of this chapter https://1coderookie.github.io/BSB-LPB-LAN_EN/chap07.html#712-notes-on-ds18b20-temperature-sensors or something similar? Or any kind of a busmaster chip..? Or..?

**Comment by Charodej** [comment]
5 sensors ds18b20 (same as in pdf manual) and adapter looks like that
![AE7402F3-ADC6-43DB-815E-E5AACDFBB7EC](https://user-images.githubusercontent.com/71496568/115223347-fca02d00-a10b-11eb-98e9-5d7834ca87fc.jpeg)

Than it goes to data pin 7.

**Comment by 1coderookie** [comment]
Ok, thanks. So if it worked before the update with that setup w/o any problems, it shouldn't be a HW-problem - but just for you to keep in mind: There _could_ occur problems due to the value of the resistor: 4k7 is good for one sensor, but the more sensors you add (and the longer the wires become), the smaller the resistor might has to become..
And now you don't get any value at all?
As fredlcore said, please post a log of the query.
I'll test asap..

**Comment by Charodej** [comment]
There is no value given by the sensors in the parametres at all - through webinterface.
I tried already 2 new versions after the working version as stated above. Last working version is the one I am actually using.

**Comment by 1coderookie** [comment]
Tested with 5 sensors, works as expected:
![Bildschirmfoto von 2021-04-19 14-00-55](https://user-images.githubusercontent.com/25869362/115233073-c10b6000-a117-11eb-8175-a0e32ffbd393.png)


Check the startup in the serial monitor (https://1coderookie.github.io/BSB-LPB-LAN_EN/chap12.html#122-serial-monitor), there should appear this (with a different timestamp though ;) ):
```
13:58:58.400 -> Init One Wire bus...
13:58:58.632 -> numSensors: 5
```
If it doesn't appear: 
Could it be that you didn't activate OneWire in the config.h? Check that setting:

// Compile module with one wire bus support.
#define ONE_WIRE_BUS
bool enableOneWireBus = **_false_**;  //true - enable oneWire bus, false - disable
byte One_Wire_Pin = 7;         // Define the pin for one wire temperature sensors

-> if "bool enableOneWireBus" is set to "false", enter "true" instead, flash again, observe the startup using serial monitor and do another test please by clicking on the "Sensors" button at the top of the BSB-LAN-page.

**Comment by Charodej** [comment]
OK right now I have sensors reading but DHT22 stop to read 
![image](https://user-images.githubusercontent.com/71496568/115238627-2f532100-a11e-11eb-97a6-af302f934644.png)

**Comment by 1coderookie** [comment]
It would be nice if you would share with us what exactly you did and why suddenly the OneWire works..

**Comment by 1coderookie** [comment]
And _again_: the full logs from the serial monitor would be helpful!

**Comment by Charodej** [comment]
I went back to the Arduino program a set 
bool enableOneWireBus = true;  //true - enable oneWire bus, false - disable
byte One_Wire_Pin = 7;    

[log.txt](https://github.com/fredlcore/BSB-LAN/files/6336182/log.txt)

**Comment by 1coderookie** [comment]
Ok, so your log shows no DHT22 at bootup (which should be the case iirc) and it says there is a timeout error when querying: 
```
Virtual parameter 20101 queried. Table line 4096
DHT22 sensor: 5 - Time out error
One Wire, DHT & MAX! Sensors
Virtual parameter 20102 queried. Table line 4097
DHT22 sensor: 5 - Time out error
One Wire, DHT & MAX! Sensors
Virtual parameter 20103 queried. Table line 4098
DHT22 sensor: 5 - Time out error
```
But I'm not sure why, it seems to me that no sensor is connected though.. 
Is the HW-setup still ok, or maybe a wire is loose or so? 
Did you change anything on the DHT22-config in the config.h-file? And/or did you check, that the settings for DHT22 (regarding the activation and the used pin(s)) are still ok?
It should still look like this (if you are using pin 5 for the DHT22; if you are using more than 1 sensor, then of course each belonging pin has to be assigned):
```
// Compile module with DHT temperature/humidity sensors support
#define DHT_BUS
// Define the pins for DHT temperature/humidity sensors (Up to 10)
byte DHT_Pins[10] = {5};
```

--

Another point: 
Are you using MAX!-components? Your log:
```
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Adding known Max ID to list: 00000000
Connection to max_cul: failed
```
If you don't have MAX!, then you can/should deactivate it.

**Comment by dukess** [comment]
@Charodej try to use version before 03.03.2021. 03-05.03 new DHT library was added.

**Comment by 1coderookie** [comment]
But we tested it with the new lib and it worked, right? So I'd guess the problem is probably somewhere in the config.h or in the hw-setup as described above..

**Comment by dukess** [comment]
Yes, Ulf, you right, it worked. But i take consideration small probability for program failure :)

**Comment by 1coderookie** [comment]
@Charodej : Any news here..?

**Comment by Charodej** [comment]
excuse me not resposding - some other priorites right now. 
Some strange things are happening in my system - both types of sensors started to work, but then as right now it is not running again. Same situation as before - so I ordered some new HW to see what is the issue...
Give me some time and come back if fixed or what was cause..

**Comment by 1coderookie** [comment]
No problem.
Make sure that  
a) you connect the sensors to 3,3V at the Due (so that the GPIOs only get 3,3V signal) and
b) you're using a sufficient power supply. In case you are using USB as power-supply, you can measure the voltage at the 3,3V and 5V pins at the DUE for example, just to check if at least the voltage is fine there.  
Good luck!

**Comment by 1coderookie** [comment]
@Charodej  : Did you get it working - can we close this issue?

**Comment by Charodej** [comment]
Hello, thank you so much for the information. At the end it was power supply issue and short circuit in one of the sensors as well. It is right now fix and everything running. Thank you for your work!
