### ISSUE TITLE
[BUG] Parameter 1498 with NULL Enum

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#372]
Hi,

I think there is an error in your definitions file. The Parameter 1498 has the type VT_ENUM, a size, but the ENUM column is NULL
```c++
{0x073D0DD4,  CAT_HKP, VT_ENUM, 1498, STR1498, sizeof(ENUM1498), NULL, DEFAULT_FLAG, DEV_ALL}, // Logged from LMS15
```

bye Konrad

**Comment by fredlcore** [comment]
Thanks, fixed.
