### ISSUE TITLE
Do we need NTP client implementation?

### ISSUE THREAD

**Issue by dukess** [fredlcore/BSB-LAN#378]
...for periodical time syncing.
We can use this solution:
https://www.arduino.cc/en/Tutorial/LibraryExamples/UdpNtpClient
or this: 
https://github.com/arduino-libraries/NTPClient
or something else.

**Comment by fredlcore** [comment]
I think this should be done through the Home Automation System which could then just use the /S0=xx.xx.xx command. This would have the same functionality and would not need extra libraries and maintainance.
