### ISSUE TITLE
[BUG] parsing of webif config creates wrong character

### ISSUE THREAD

**Issue by SebastianJuch** [fredlcore/BSB-LAN#381]
**BSB-LAN Version**
#define MAJOR "2"
#define MINOR "0"
#define PATCH "99"
#define COMPILETIME "20210624231250"

**Architecture**
ESP32 NodeMCU

**Bus system**
BSB

**Describe the bug**
After saving config settings over the webif, the SSID (stored in BSB_LAN_config.h) get's manipulated if it has spaces. 

**To Reproduce**
1. Set the SSID in BSB_LAN_config.h to a name with spaces "The Nexus"
2. compile and flash
3. Open WebIf
4. SSID will shown correctly (see before.png)
5. Change one Setting (as example enable mqqt service) and press save
6. SSID is showing now "The+Nexus"

**Logs**
/

**Expected behavior**
SSID is not changing

**Screenshots**
before.png
![before](https://user-images.githubusercontent.com/16326958/126206404-7f45a381-faa8-4154-b10e-d3b1244ada75.png)
after.png
![after](https://user-images.githubusercontent.com/16326958/126206456-40a191c4-e816-44b1-ab22-338722e0b98e.png)

**Desktop (if applicable, please complete the following information):**
 - OS: WIN10
 - Browser Chrome up to date
 - Version last

**Smartphone (if applicable, please complete the following information):**
/

**Additional context**
/

**Comment by dukess** [comment]
Thanks for report!
Here is no strings conversion to URL format and vice versa so we got this unsatisfactory behavior.

**Comment by fredlcore** [comment]
Thanks, @dukess!

**Comment by SebastianJuch** [comment]
Thanks for fixing!
