### ISSUE TITLE
Telnet no longer working?

### ISSUE THREAD

**Issue by fredlcore** [fredlcore/BSB-LAN#387]
I just realized that currently, it seems no longer possible to use the Telnet connection to monitor bus telegrams.
If Telnet is selected as debug output, you can connect to the IP address, but after printing the version, the connection gets disconnected.
It seems that `telnetClient.connected()` evaluates to 0/false and thus the subsequent code stops the telnetClient.
The strange thing is that right before the if-clause which checks for `telnetClient.connected()`, I can add several lines doing a `telnetClient.println(telnetClient.connected())` - and I always get a 1/true.

I was suspecting another maximum socket problem, but since this change happens right in the same if-clause (from currently line 9186 onwards), that does not seem to be the case. Any ideas?

**Comment by dukess** [comment]
Yes, this may be one of the non-obvious errors that was not a bug on some architectures/libraries.

**Comment by fredlcore** [comment]
Thanks!
