### ISSUE TITLE
String won't get populated over MQTT for parameter 8730

### ISSUE THREAD

**Issue by olympia** [fredlcore/BSB-LAN#428]
**BSB-LAN Version**
#define MAJOR "2"
#define MINOR "0"
#define PATCH "108"
#define COMPILETIME "20211114123620"

**Architecture**
ESP32 Olimex EVB

**Bus system**
BSB

**Describe the bug**
For parameter 8730 only the value (e.g. 0) gets populated and the associated string is missing (e.g. Off).

**To Reproduce**
Should be visible in MQTT explorer

**Logs**
N/A

**Expected behavior**
String should be next to the value, like for any other parameters. Should be "0 - Off" instead of just "0"

**Screenshots**
![image](https://user-images.githubusercontent.com/1816315/147487189-e09045ca-4c45-4f78-96ef-8f257fad8671.png)

**Desktop (if applicable, please complete the following information):**
N/A

**Smartphone (if applicable, please complete the following information):**
N/A

**Additional context**
N/A

**Comment by 1coderookie** [comment]
Please make an update of BSB-LAN first and try again. If it's still the same, please report it again here.

**Comment by fredlcore** [comment]
Also, please check if this problem also occurs with other parameters or only with this one. And please compare the MQTT output with the output of the Webinterface to see if the problem exists there, too.

**Comment by olympia** [comment]
I updated to v2.0.111 and the problem persists (by the way I had to revert the change in line 513 of BSB_LAN.ino otherwise I couldn't compile).

I attached a screenshot to the report where it is visible that from the selected parameters exposed to MQTT only this is having the issue (see last two lines of the screenshot).

Web interface doesn't have this issue:

Screenshots:
![image](https://user-images.githubusercontent.com/1816315/147506401-a3c5815c-eebb-4203-a6d2-864dfe92b1a8.png)

![image](https://user-images.githubusercontent.com/1816315/147506439-ba77c56c-00e0-48af-b9ef-44ddc477fc65.png)

**Comment by fredlcore** [comment]
I think I found the bug, should be fixed in the current master repo. Please try and report back here, thanks!

**Comment by olympia** [comment]
Hi Frederik,

Great, I confirm the issue is fixed! Many thanks!

Do you have an idea/ hint why I cannot compile with `EEPROMClass EEPROM_ESP((const char *)PSTR("nvs"));` being in line 513 of BSB_LAN.ino and I have to revert it back to `EEPROMClass EEPROM_ESP("nvs", EEPROM_SIZE);` to get a successful compile?
Shall I open a separate issue for this? ...but I guess this is more of a support query :)

I get the following errors:
```
BSB_LAN:513:49: error: invalid conversion from 'const char*' to 'uint32_t {aka unsigned int}' [-fpermissive]
 EEPROMClass EEPROM_ESP((const char *)PSTR("nvs"));
                                                 ^
In file included from C:\Users\olympia\Downloads\BSB_lan\BSB_LAN\BSB_LAN.ino:505:0:
C:\Users\olympia\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\EEPROM\src/EEPROM.h:37:5: note:   initializing argument 1 of 'EEPROMClass::EEPROMClass(uint32_t)'
     EEPROMClass(uint32_t sector);
     ^
Multiple libraries were found for "WiFi.h"
 Used: C:\Users\olympia\AppData\Local\Arduino15\packages\esp32\hardware\esp32\1.0.6\libraries\WiFi
 Not used: C:\Program Files (x86)\Arduino\libraries\WiFi
exit status 1
invalid conversion from 'const char*' to 'uint32_t {aka unsigned int}' [-fpermissive]
```

**Comment by fredlcore** [comment]
You haven't installed SDK 2.0.2 completely/properly. As you can see, it is still using the EEPROM library from 1.0.6 whereas it should be using the one from 2.0.2. Either try to update the EEPROM library from the library manager or uninstall and then reinstall the ESP32 board or - if all this fails - uninstall and reinstall the Arduino IDE from scratch. Please let us know which way works in the end so we can add this to our FAQ.

**Comment by olympia** [comment]
Spot on.! 
To install SDK 2.0.2 I had to reinstall ESP32 board by adding/ replacing the "Additional board manager URLs" in File/Preferences in Arduino IDE to include:
https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
...and then I could update ESP32 board to 2.0.2

**Comment by fredlcore** [comment]
Great, that's how it is mentioned in the manual now as well, so we won't have to add anything to the FAQ then, thanks!

**Comment by olympia** [comment]
Well, not entirely. The link is different in the manual and using that link v1.0.6 would be the latest.
This is actually what I had as well on my install and I had to replace this with the link above to enable the installation/ update to v2.0.2

**Comment by fredlcore** [comment]
Are you referring to the PDF manual or the one on GitHub? On the latter (https://1coderookie.github.io/BSB-LPB-LAN_EN/chap12.html#121-installation) we have updated everything accordingly already. The PDF will take a few days more.

**Comment by olympia** [comment]
Right, I was looking at the pdf now. I now see the update on the online
version from 3 days ago. All is fine :)
Thank you!

**Comment by 1coderookie** [comment]
I updated the PDF at the same time though, so you probably weren't looking at the PDF from the latest download..?
![Bildschirmfoto von 2021-12-28 09-14-45](https://user-images.githubusercontent.com/25869362/147544854-6bba520f-4d45-40fc-bc6d-0fb6805a8687.png)

**Comment by olympia** [comment]
yes, yes; sorry for the noise :)
