### ISSUE TITLE
2.0 Show "New Vision found"

### ISSUE THREAD

**Issue by Saharel001** [fredlcore/BSB-LAN#435]
**BSB-LAN Version**
2.0

**Describe the bug**
In Version 2.0 i get a new version found 2.1.0 massage but in git the last release is 2.0.0

**Screenshots**
![Screenshot 2022-01-11 090430](https://user-images.githubusercontent.com/24453343/148903922-44193ec9-35b4-4449-8e1c-e6cabed8e32e.png)

**Comment by dukess** [comment]
Current development version is 2.1.0, so it is correct. But last released version is 2.0.0, you right.

**Comment by Saharel001** [comment]
@dukess 
Its ok for me, but in my opinion ist a dev version not a stable release. But it´s possible that my interpretation from "New Version Found" ist wrong ;)

**Comment by 1coderookie** [comment]
We never claimed that a dev version is a stable release - but I'll add a note to the manual, that 'show updates' also includes dev versions..
