### ISSUE TITLE
Platform.IO Build EEPROM invalid conversion

### ISSUE THREAD

**Issue by Drocona** [fredlcore/BSB-LAN#447]
Hi,

I've been trying to get the build for BSB-LAN to work for this entire weekend already and I just can't seem to make it work. I've followed the steps from the manual but during the build I get the following output:
`C:/Dev/BSB-LAN/BSB-LAN/BSB_LAN.ino:518:29: error: invalid conversion from 'const char*' to 'uint32_t {aka unsigned int}' [-fpermissive]
Compiling .pio\build\esp32-evb\src\src\SdFat\MinimumSerial.cpp.o
 EEPROMClass EEPROM_ESP("nvs");
                             ^
In file included from C:/Dev/BSB-LAN/BSB-LAN/BSB_LAN.ino:509:0:
C:\Users\User\.platformio\packages\framework-arduinoespressif32\libraries\EEPROM\src/EEPROM.h:37:5: note:   initializing argument 1 of 'EEPROMClass::EEPROMClass(uint32_t)'
     EEPROMClass(uint32_t sector);
     ^`

As you can see I've already tried to adjust `Class EEPROM_ESP((const char *)PSTR("nvs"));` to `EEPROMClass EEPROM_ESP("nvs");` based on the only issue I could find containing EEPROM #420, but that doesn't change anything.

**Comment by fredlcore** [comment]
No need to change anything, just use the correct board URL that is also mentioned in our manual. Otherwise the Arduino IDE does not use the most recent ESP32 SDK.
