### ISSUE TITLE
[BUG] v2.0 fails to build for ESP32 while master works (Arduino IDE 1.8.19, ESP32 2.0.3)

### ISSUE THREAD

**Issue by designer2k2** [fredlcore/BSB-LAN#454]
**BSB-LAN Version**
2.0.113-20211231181308

**Architecture**
ESP32 Dev Board

**Describe the bug**
It fails to build the OneWire lib, at least that what it looks to me.

**To Reproduce**
1. Download v2.0 Release: https://github.com/fredlcore/BSB-LAN/releases/tag/v2.0
2. Use latest Arduino IDE (1.8.19) and ESP32 Board (2.0.3)
3. Setup according to manual (remove not needed folders, rename config)
4. Press upload, it builds for a while and then fails.

**Logs**
Build Log from the failing part:
```
In file included from C:\Users\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.3\cores\esp32/Arduino.h:36,
                 from C:\Users\Arduino\homeautomation\bsb_zeugs\sw20\BSB_LAN\src\OneWire\OneWire.cpp:142:
C:\Users\Arduino\homeautomation\bsb_zeugs\sw20\BSB_LAN\src\OneWire\util\OneWire_direct_gpio.h: In function 'void directModeInput(uint32_t)':
C:\Users\Arduino\homeautomation\bsb_zeugs\sw20\BSB_LAN\src\OneWire\util\OneWire_direct_gpio.h:191:38: error: 'esp32_gpioMux' was not declared in this scope
         ESP_REG(DR_REG_IO_MUX_BASE + esp32_gpioMux[pin].reg) = pinFunction;
                                      ^~~~~~~~~~~~~
C:\Users\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.3\cores\esp32/esp32-hal.h:73:47: note: in definition of macro 'ESP_REG'
 #define ESP_REG(addr) *((volatile uint32_t *)(addr))
                                               ^~~~
C:\Users\Arduino\homeautomation\bsb_zeugs\sw20\BSB_LAN\src\OneWire\util\OneWire_direct_gpio.h: In function 'void directModeOutput(uint32_t)':
C:\Users\Arduino\homeautomation\bsb_zeugs\sw20\BSB_LAN\src\OneWire\util\OneWire_direct_gpio.h:232:38: error: 'esp32_gpioMux' was not declared in this scope
         ESP_REG(DR_REG_IO_MUX_BASE + esp32_gpioMux[pin].reg) = pinFunction;
                                      ^~~~~~~~~~~~~
C:\Users\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.3\cores\esp32/esp32-hal.h:73:47: note: in definition of macro 'ESP_REG'
 #define ESP_REG(addr) *((volatile uint32_t *)(addr))
                                               ^~~~
```

**Expected behavior**
It should build.

**Desktop (if applicable, please complete the following information):**
 - OS: Win 10
 - Arduino IDE: 1.8.19
 - ESP32: 2.0.3

**Additional context**
When using the very latest master from github (2.1.3-20220209235153) it builds right away and works.

**Comment by fredlcore** [comment]
If the latest Master works, but not the release version 2.0, then it's either a bug or a dependency that causes this problem. Since we do not update past releases, I'll try to get a more current release out there soon. Thanks for the info!
