### ISSUE TITLE
[BUG]?: Menu entry to display log file is disabled when logging is turned off - although "old" log file exists

### ISSUE THREAD

**Issue by DE-cr** [fredlcore/BSB-LAN#472]
The behavior described in this issue's subject was unexpected to me.
However, it may have been an intentional design decision, i.e. not a bug.

**Comment by DE-cr** [comment]
...the "old" log file can still be accessed by directly entering the corresponding url commands, though (e.g. /DG).

**Comment by fredlcore** [comment]
Logging and log file are two different things, so there is no contradiction.

**Comment by DE-cr** [comment]
Just to better explain what I mean:
Having this configuration option unchecked:
![image](https://user-images.githubusercontent.com/105788188/185548037-a1b97a32-20ca-4b86-8d2a-154658095e00.png)
...disables the "Ausgabe Logdatei" menu entry - even when such a "Logdatei" does exist:
![image](https://user-images.githubusercontent.com/105788188/185548423-c9a1be56-c19b-4e37-92d3-7b523c2d78ac.png)

With the above mentioned configuration option enabled, the menu entry is enabled (and now reads "Zeichne Logdatei", calling /DG).

**Comment by fredlcore** [comment]
Yes, I understood. The alternative would be to either delete the log file when turning off logging (not a good idea if done unintentionally) or to keep the menu item active even when logging is turned off (which could give the impression that logging is still active). Both is not ideal and the current way is both non-destructive and shows the logging status at first glance.
