### ISSUE TITLE
[BUG] Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

### ISSUE THREAD

**Issue by jonasenders** [fredlcore/BSB-LAN#490]
**BSB-LAN Version**
Version: 2.1.8-20220731102301

**Architecture**
ESP32 NodeMCU

**Bus system**
PPS

**Describe the bug**
I am trying to integrate the BSB-LAN into Home Assistant. As soon as the integration tries to call " /JQ?Parameter=6224,6225,6226" this error occurs and the esp32 restarts.

**Logs**
`POST /JQ?Parameter=6224,6225,6226 HTTP/1.1

00 3D 00 00 00 00 00 00 00
#6224:  unknown command
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x40089e69  PS      : 0x00060d30  A0      : 0x800d376b  A1      : 0x3ffb24e0  
A2      : 0x3ffc3b65  A3      : 0x00000000  A4      : 0x000000ff  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x00000000  A9      : 0x3ffb2100  
A10     : 0x3ffc3b65  A11     : 0xffffffff  A12     : 0x0000001a  A13     : 0x3ffb2310  
A14     : 0x0000001a  A15     : 0x3ffb2310  SAR     : 0x00000004  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000000  LBEG    : 0x40089e69  LEND    : 0x40089e76  LCOUNT  : 0xffffffff  

Backtrace:0x40089e66:0x3ffb24e00x400d3768:0x3ffb24f0 0x400d37f3:0x3ffb2510 0x400dce63:0x3ffb2530 0x400ecbb1:0x3ffb2820 

ELF file SHA256: 0000000000000000`

**Comment by fredlcore** [comment]
Well, it would of course be nice if a malformed request would not result in a reboot, but where did you get this syntax from? The correct way would be to GET /JQ=6224,6225,6226
