### ISSUE TITLE
[BUG] Ja/Nein-Text statt früher passender Ein/Aus

### ISSUE THREAD

**Issue by DE-cr** [fredlcore/BSB-LAN#500]
Pumpenstati 0/255 aus /K61 werden neuerdings mit Nein/Ja übersetzt anstatt wie früher passender mit Aus/Ein.
Pumpe=Ja/Nein klingt wie Pumpe vorhanden/n.v. Hier wird aber angegeben ob die (vorhandene) Pumpe momentan läuft oder nicht.
Betrifft z.B. die Parameter 8760.0 und 8820.0.

Festgestellt mit GitHub-Stand vom 6.10.2022, ca. 21:10 MESZ.

**Comment by fredlcore** [comment]
That was a bug, will be fixed, thanks.
