### ISSUE TITLE
[BUG] duplicate in defs

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#501]
Hi,

any reason to have this entry double, this is exactly the same

https://github.com/fredlcore/BSB-LAN/blob/master/BSB_LAN/BSB_LAN_custom_defs.h.default#L7345

https://github.com/fredlcore/BSB-LAN/blob/master/BSB_LAN/BSB_LAN_custom_defs.h.default#L7348

**Comment by fredlcore** [comment]
Yes, to match/ignore both of these when scanning for new parameters.
