### ISSUE TITLE
[BUG] translation CS / duplicate / not needed

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#502]
please check:

localization/LANG_CS.h:302:9: warning: 'STR2322_TEXT' macro redefined [-Wmacro-redefined]
#define STR2322_TEXT "Max. otáčky čerpadla"
        ^
localization/LANG_CS.h:301:9: note: previous definition is here
#define STR2322_TEXT "Min. otáčky čerpadla"

On top I expect all that entries are not used if I use this query:

https://github.com/fredlcore/BSB-LAN/search?l=C%2B%2B&q=STR2322

**Comment by fredlcore** [comment]
Yes, there are several doublettes due to several users apparently adding translations. But due to the changes we are pursuing currently (https://github.com/fredlcore/BSB-LAN/discussions/482), these files will become irrelevant anyways in the near future, so this will become obsolete then.
