### ISSUE TITLE
[BUG] translation HU - cleanup

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#503]
all that strings are double for a given STR Id and this override does not make sense:

rc/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:644:9: warning: 'STR6112_TEXT' macro redefined [-Wmacro-redefined]
#define STR6112_TEXT "Helyiség modell meredekség"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:522:9: note: previous definition is here
#define STR6112_TEXT "Gradient Raummodell"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:645:9: warning: 'STR6120_TEXT' macro redefined [-Wmacro-redefined]
#define STR6120_TEXT "Rendszer fagyvédelem"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:526:9: note: previous definition is here
#define STR6120_TEXT "Fagyvédelmi üzem"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:646:9: warning: 'STR6127_TEXT' macro redefined [-Wmacro-redefined]
#define STR6127_TEXT "Időtartam szivattyú / váltószelep megjáratáshoz"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:527:9: note: previous definition is here
#define STR6127_TEXT "Szivattyú/szelep járatás időtartam"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:647:9: warning: 'STR6220_TEXT' macro redefined [-Wmacro-redefined]
#define STR6220_TEXT "Készülék-SW-verzió"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:560:9: note: previous definition is here
#define STR6220_TEXT "Szoftver-verzió"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:648:9: warning: 'STR6225_TEXT' macro redefined [-Wmacro-redefined]
#define STR6225_TEXT "Készülék-család"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:565:9: note: previous definition is here
#define STR6225_TEXT "Készülékcsalád"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:649:9: warning: 'STR6226_TEXT' macro redefined [-Wmacro-redefined]
#define STR6226_TEXT "Készülék-változat"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:566:9: note: previous definition is here
#define STR6226_TEXT "Készülékvariáns"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:650:9: warning: 'STR6227_TEXT' macro redefined [-Wmacro-redefined]
#define STR6227_TEXT "Készülék-OV-verzió"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:567:9: note: previous definition is here
#define STR6227_TEXT "Objektumkönyvtár-verzió"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:651:9: warning: 'STR6230_TEXT' macro redefined [-Wmacro-redefined]
#define STR6230_TEXT "Szabályozó konfiguráció 0"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:570:9: note: previous definition is here
#define STR6230_TEXT "KonfigRg0 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:652:9: warning: 'STR6240_TEXT' macro redefined [-Wmacro-redefined]
#define STR6240_TEXT "Szabályozó konfiguráció 1"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:578:9: note: previous definition is here
#define STR6240_TEXT "KonfigRg1 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:653:9: warning: 'STR6250_TEXT' macro redefined [-Wmacro-redefined]
#define STR6250_TEXT "Szabályozó konfiguráció 2"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:589:9: note: previous definition is here
#define STR6250_TEXT "KonfigRg2 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:654:9: warning: 'STR6260_TEXT' macro redefined [-Wmacro-redefined]
#define STR6260_TEXT "Szabályozó konfiguráció 3"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:600:9: note: previous definition is here
#define STR6260_TEXT "KonfigRg3 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:655:9: warning: 'STR6270_TEXT' macro redefined [-Wmacro-redefined]
#define STR6270_TEXT "Szabályozó konfiguráció 4"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:601:9: note: previous definition is here
#define STR6270_TEXT "KonfigRg4 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:656:9: warning: 'STR6300_TEXT' macro redefined [-Wmacro-redefined]
#define STR6300_TEXT "Szabályozó konfiguráció 7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:608:9: note: previous definition is here
#define STR6300_TEXT "KonfigRg7 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:657:9: warning: 'STR6330_TEXT' macro redefined [-Wmacro-redefined]
#define STR6330_TEXT "Szabályozó konfiguráció 10"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:611:9: note: previous definition is here
#define STR6330_TEXT "KonfigRg10 Bit 0-7"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:971:9: warning: 'STR8950_TEXT' macro redefined [-Wmacro-redefined]
#define STR8950_TEXT "Közös előremenő aktuális hőmérséklet"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:963:9: note: previous definition is here
#define STR8950_TEXT "Processz szignál aktuális előremenő hőmérséklet"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:972:9: warning: 'STR8951_TEXT' macro redefined [-Wmacro-redefined]
#define STR8951_TEXT "Közös előremenő hőmérséklet alapjel"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:964:9: note: previous definition is here
#define STR8951_TEXT "Processz szignál előremenő hőmérséklet alapjel"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:973:9: warning: 'STR8952_TEXT' macro redefined [-Wmacro-redefined]
#define STR8952_TEXT "Közös visszatérő aktuális hőmérséklet"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:965:9: note: previous definition is here
#define STR8952_TEXT "Processz szignál visszatérő hőmérséklet"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:975:9: warning: 'STR8980_TEXT' macro redefined [-Wmacro-redefined]
#define STR8980_TEXT "Puffer 1 aktuális hőmérséklet"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_HU.h:966:9: note: previous definition is here
#define STR8980_TEXT "Puffertároló hőm. aktuális érték felül (B4)"

**Comment by fredlcore** [comment]
See https://github.com/fredlcore/BSB-LAN/issues/502
