### ISSUE TITLE
[BUG] translation NL - cleanup

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#504]
see the errors:

In file included from src/main.cpp:19:
In file included from src/../../bsb_lan/BSB_LAN/BSB_LAN_defs.h:23:
src/../../bsb_lan/BSB_LAN/localization/LANG_NL.h:434:9: warning: 'STR2730_TEXT' macro redefined [-Wmacro-redefined]
#define STR2730_TEXT "Ionisatiestroom"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_NL.h:267:9: note: previous definition is here
#define STR2730_TEXT "Ionisatie"
        ^
In file included from src/main.cpp:19:
In file included from src/../../bsb_lan/BSB_LAN/BSB_LAN_defs.h:1052:
src/../../bsb_lan/BSB_LAN/BSB_LAN_custom_defs.h:2647:9: warning: 'ENUM880_02_TEXT' macro redefined [-Wmacro-redefined]
#define ENUM880_02_TEXT STR2317_TEXT
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_NL.h:562:9: note: previous definition is here
#define ENUM880_02_TEXT "Temperatuurslag nominaal"
        ^
In file included from src/main.cpp:19:
In file included from src/../../bsb_lan/BSB_LAN/BSB_LAN_defs.h:1052:
src/../../bsb_lan/BSB_LAN/BSB_LAN_custom_defs.h:3511:9: warning: 'ENUM8000_70_TEXT' macro redefined [-Wmacro-redefined]
#define ENUM8000_70_TEXT STR2262_TEXT
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_NL.h:629:9: note: previous definition is here
#define ENUM8000_70_TEXT "Opstart optimalisatie"
        ^
In file included from src/main.cpp:19:
In file included from src/../../bsb_lan/BSB_LAN/BSB_LAN_defs.h:1052:
src/../../bsb_lan/BSB_LAN/BSB_LAN_custom_defs.h:3512:9: warning: 'ENUM8000_71_TEXT' macro redefined [-Wmacro-redefined]
#define ENUM8000_71_TEXT STR770_TEXT
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_NL.h:630:9: note: previous definition is here
#define ENUM8000_71_TEXT "Snelvoorverwarming"
        ^
In file included from src/main.cpp:19:
In file included from src/../../bsb_lan/BSB_LAN/BSB_LAN_defs.h:1052:
src/../../bsb_lan/BSB_LAN/BSB_LAN_custom_defs.h:3513:9: warning: 'ENUM8000_76_TEXT' macro redefined [-Wmacro-redefined]
#define ENUM8000_76_TEXT ENUM702_00_TEXT
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_NL.h:635:9: note: previous definition is here
#define ENUM8000_76_TEXT "Zomerstand"

**Comment by fredlcore** [comment]
See https://github.com/fredlcore/BSB-LAN/issues/502
