### ISSUE TITLE
[BUG] translation - TR cleanup

### ISSUE THREAD

**Issue by konne** [fredlcore/BSB-LAN#505]
see the logs

src/../../bsb_lan/BSB_LAN/localization/LANG_TR.h:14:9: warning: 'ENUM_CAT_07_TEXT' macro redefined [-Wmacro-redefined]
#define ENUM_CAT_07_TEXT "Zaman programi ist dev 3/P"
        ^
src/../../bsb_lan/BSB_LAN/localization/LANG_TR.h:11:9: note: previous definition is here
#define ENUM_CAT_07_TEXT "Zaman programi ist dev 2"

**Comment by fredlcore** [comment]
See https://github.com/fredlcore/BSB-LAN/issues/502

**Comment by fredlcore** [comment]
Actually, this is another good example why the previous approach of a "one definition file for all heaters" has never really worked (different category enumeration for different heaters)
