### ISSUE TITLE
[BUG] decoding error for parameter 6224

### ISSUE THREAD

**Issue by DE-cr** [fredlcore/BSB-LAN#526]
**BSB-LAN Version**
3.0.3-20221119003550

**Architecture**
ESP32 NodeMCU

**Bus system**
BSB

**Describe the bug**
/6224 shows on my system (boiler=SPK14B):
`6224 Uhrzeit - Geräte-Identifikation: 52565334332E3132322F32303000000000 - decoding error`

**Comment by fredlcore** [comment]
Again, there was an already fixed error. This time in the generation of the _custom_defs.h, so apparently you are using one where this output was still a problem. You can fix this one yourself by setting the type of 6224 to VT_STRING.
If you want to continue checking every parameter, please contact me for an up to date _custom_defs.h, so we can avoid opening and closing issues that are already taken care of.
