### ISSUE TITLE
[BUG]? averages use even param numbers only

### ISSUE THREAD

**Issue by DE-cr** [fredlcore/BSB-LAN#561]
Introduced with 3.1.4-20230321214015 (?):

When selecting four parameters for averages calculation, they now occupy the virtual parameter numbers
20050, 20052, 20054, 20056, as opposed to
20050, 20051, 20052, 20053 previously.

Is this intended?

![image](https://user-images.githubusercontent.com/105788188/227028747-19b01ca1-45ec-42bc-a43f-a1f0d2713e82.png)

**Comment by fredlcore** [comment]
Yes, that was a bug, thanks for noticing. Fixed in master.
