### ISSUE TITLE
[QUESTION] Removing Led

### ISSUE THREAD

**Issue by ferllings** [fredlcore/BSB-LAN#587]
Hello,
Thanks for your amazing work !

I'm testing my heat pump with a prototype board based on the documentation Circuit Diagram.
BSB-Lan seems to work fine, I can see the data in the interface.

But the LED is always ON (and sometimes flickering)
1) Is it supposed to be On all the time?
2) Can I remove it from the circuit?

Thanks

**Comment by fredlcore** [comment]
1) Yes
2) No
