### ISSUE TITLE
[FEATURE REQUEST] Provide older Version for Arduino Mega 2560 boards

### ISSUE THREAD

**Issue by litronics** [fredlcore/BSB-LAN#600]
**Is your feature request related to a problem? Please describe.**
I am running BSB-LAN on my older Mega 2560 boards and need to update some settings which are hardcoded in the source.

**Describe the solution you'd like**
It would be great if you are able to provide the latest source code which still runs on the Mega board.

**Describe alternatives you've considered**
none

**Comment by fredlcore** [comment]
As mentioned in the manual and also in the ChangeLog in BSB_LAN.ino, version 0.41 is the last one to run on the Mega. It can be downloaded under "Releases".
