### ISSUE TITLE
[FEATURE REQUEST] Send BSB-LAN version to MQTT

### ISSUE THREAD

**Issue by Toniob** [fredlcore/BSB-LAN#611]
Hi,

I think it will be great if BSB-LAN was sending its version to MQTT. Maybe on a topic like /version . That way, we could retrieve this string in Home Assistant (or elsewhere).

What do you think ?

**Comment by Toniob** [comment]
Other informations like the IP Address or the mdns name should be useful to put on the device part of the homeassistant mqtt configuration.

**Comment by fredlcore** [comment]
Since I'm not a MQTT user, my experience in this area is very limited. So if someone adds the required code (after we have discussed here what exactly is necessary), I'm happy to include this in the code, but I won't have the resources to do that.
