### ISSUE TITLE
[FEATURE REQUEST] No wifi if started after wifi access point

### ISSUE THREAD

**Issue by barbuslex** [fredlcore/BSB-LAN#618]
Hi, 
I realized that if bsb-lan is started before wifi access point it never gets wifi connection.
Is there an option to make bsb-lan search for wifi again if it can't find it on startup?

I have see an article here : https://randomnerdtutorials.com/solved-reconnect-esp32-to-wifi/

Thanks

**Comment by fredlcore** [comment]
If you have defined a WiFi network and the network is not available (for whatever reason), BSB-LAN starts its own access point for 30 minutes before trying again to connect to the network defined in the configuration. So it already does what you want it to do.
