### ISSUE TITLE
[FEATURE REQUEST] Set date and time

### ISSUE THREAD

**Issue by barbuslex** [fredlcore/BSB-LAN#621]
Hi,

When i try to set date and time on sensor number 0 after one minute the date and time is reset to 01.01.2015 00:00:00.

Here an exemple of the request : http://BSBLANIP/S0=27.02.2024_13:12:23

Is it possible to set date and time on another way ?

Thanks

**Comment by fredlcore** [comment]
This is a bug report, not a feature request. Open up a bug report and provide all the required information and I'll have a look at it.
