### ISSUE TITLE
[FEATURE REQUEST] Add support for WT32-ETH1 board

### ISSUE THREAD

**Issue by jbaudoux** [fredlcore/BSB-LAN#626]
I don't know yet if supporting such board will be easy or not but as I planned to use such board and willing to make the required changes   I open an issue for logging the findings.

WT32-ETH1 is esp32 board with a built-in Ethernet port. This board simplifies the hardware when you need a wired LAN connection as you don't need a additional Ethernet board.

**Comment by fredlcore** [comment]
For that, we support the Olimex EVB which comes with built-in Ethernet. The WT32-ETH1 does not have a pinout that is compatible to the adapters supported by this project, it also does not seem to have a USB port for uploading BSB-LAN without additional hardware. Both aspects mean it's not going to be working out-of-the-box, even more so if it should require the use of a different Ethernet library. All of this means more support work for me with no real benefit. If it's for the form factor, the Olimex POE-ISO is almost as small, and the single digit difference in price is not a compelling argument for me.

If it's possible to get it working solely by making use of BSB_LAN_custom_*.h files, I'm perfectly fine to add it to our library, but I won't entertain any changes in the code that go beyond that. However, feel free to log any findings here in case there are others who also want to go down that road for some reason.

**Comment by fredlcore** [comment]
Watch out that the auto-detection for the RX/TX pins match. If the board behaves like a Joy-It NodeMCU, that should be the GPIOs 16 and 17, but you can check in the boot messages. I'm not sure if these are both accessible on your board, but if they are, then it should work in the same way as the Olimex.
