### ISSUE TITLE
[BUG] Compilation issue when building for OLIMEX ESP32-POE-ISO

### ISSUE THREAD

**Issue by Nivalam** [fredlcore/BSB-LAN#660]
**BSB-LAN Version**
I'm using the master branch from today:
#define MAJOR "4"
#define MINOR "0"
#define PATCH "54"
#define COMPILETIME "20240710011102"

**Architecture**
Olimex ESP32-POE-ISO   

**Bus system**
BSB

**Describe the bug**
I followed "Installing the Arduino IDE and flashing BSB-LAN" on this documentation : https://docs.bsb-lan.de/install.html
It looks like I can't compile the sofware.
This error log is during  11. Sketch/Upload

**Log files - Bug reports without log files will be closed**
```
Arduino: 1.8.19 (Linux), Board: "OLIMEX ESP32-POE-ISO, Disabled (WROOM), Minimal SPIFFS (1.9MB APP with OTA/190KB SPIFFS), QIO, 80MHz, 4MB (32Mb), 460800, None, Disabled"

WARNING: Category 'Sound' in library ESP_I2S is not valid. Setting to 'Uncategorized'
WARNING: Category 'Sensor' in library ESP_NOW is not valid. Setting to 'Uncategorized'
WARNING: Category 'Sound' in library ESP_SR is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library ESP Insights is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library ESP RainMaker is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library TFLite Micro is not valid. Setting to 'Uncategorized'
WARNING: Category '' in library WiFiProv is not valid. Setting to 'Uncategorized'
panic: runtime error: index out of range [14] with length 14

goroutine 1 [running]:
arduino.cc/builder.(*includeCache).Next(...)
	arduino.cc/builder/container_find_includes.go:209
arduino.cc/builder.findIncludesUntilDone(0xc000051000, 0xc00057c000, {{0x52b760, 0xc000078050}, {0xc000281521, 0x18}})
	arduino.cc/builder/container_find_includes.go:321 +0x1190
arduino.cc/builder.(*ContainerFindIncludes).Run(0xc00006c1a0?, 0xc000051000)
	arduino.cc/builder/container_find_includes.go:149 +0xbe5
arduino.cc/builder.runCommands(0x38?, {0xc00060dc58?, 0x22, 0x415b0b?}, 0x55?)
	arduino.cc/builder/builder.go:191 +0xda
arduino.cc/builder.(*Builder).Run(0x7ffce6a60bf7?, 0x19?)
	arduino.cc/builder/builder.go:124 +0x890
arduino.cc/builder.RunBuilder(...)
	arduino.cc/builder/builder.go:222
main.main()
	arduino.cc/arduino-builder/main.go:338 +0xa1f
arduino-builder returned 2
Error compiling for board OLIMEX ESP32-POE-ISO.
```

**Expected behavior**
Compilation and upload working

**Desktop (if applicable, please complete the following information):**
I'm using debian bookworm

**Attach your BSB_LAN_config.h file to your bug report (remove any confidential information if necessary). Do not ZIP or otherwise compress it. Bug reports without this file attached will be closed immediately.**
[BSB_LAN_config.txt](https://github.com/user-attachments/files/16240640/BSB_LAN_config.txt)

**Comment by fredlcore** [comment]
No, you did not follow the instructions as the version of the Arduino IDE you are using (1.8.19) was released almost three years ago. Currently, version 2.3.2 is the most up-to-date version. While it should still be possible to compile on older versions as well, the additional necessary steps to do so aren't listed in our manual, so you are not advised to do so.
But in case you still want to pursue this path, it seems that something is wrong with your Arduino IDE installation, as a very similar error was discussed here: https://github.com/espressif/arduino-esp32/issues/5825
But again, there is no support from me for outdated versions. You have to use the most recent versions for me to provide further assistance.
