### ISSUE TITLE
[BUG] outdated change log reference

### ISSUE THREAD

**Issue by DE-cr** [fredlcore/BSB-LAN#673]
http://bsb-lan/:
"Überprüfe auf neuere Version...
Neuere Version gefunden: [4.2.17](https://github.com/fredlcore/BSB-LAN/archive/master.zip)
Achtung! Neue Version kann Änderungen enthalten, die Anpassungen erforderlich machen. Bitte das ChangeLog in der Datei BSB_LAN.ino lesen!"

BSB_LAN.ino:
"ChangeLog has moved to separate file docs/CHANGELOG.md"

Den Umweg könnte man den Anwendern ersparen. ;)

**Comment by fredlcore** [comment]
Danke, ist erledigt...
