### ISSUE TITLE
Update / Version Check is not checking against Release Version

### ISSUE THREAD

**Issue by manoloxxl** [fredlcore/BSB-LAN#690]
**Version of the Arduino IDE**  
2.3.4

**Version of the ESP32 or Arduino framework**  
1.8.6

**BSB-LAN Version**  
4.2.27-20241125034124

**Architecture**  
Olimex EVB-POE

**Bus system**  
BSB

**Describe the bug**  
The Update / Version Check on the Startpage of the BSB is not checking against released version. It seems to check against development version.
Recently i can see and download 4.1. on Github:
#define MAJOR "4"
#define MINOR "1"
#define PATCH "11"
#define COMPILETIME "20241107004949"

But the GUI shows a 4.2.42 (Master.Zip) instead of the 4.1 Version "offical release" version.

**To Reproduce**  
1. Open http://bsb-lan.local
2. Open https://github.com/fredlcore/BSB-LAN/releases
3. Compare versions

**Expected behavior**  
I would expect to just see released versions in the update check. Or instead of this a selection in the "Update check" settings for "Off/Release/Latest"

**Screenshots**  
![image](https://github.com/user-attachments/assets/c97dce87-5e9f-49aa-8d9a-7ba7833fcfda)

**Desktop (if applicable, please complete the following information):**  
MacOS, Safari

Greetings
Manuel

**Comment by fredlcore** [comment]
Yes, that is intended behaviour. The release version is more of a "least common denominator". As mentioned in the manual, we encourage users to always use the newest version (after checking for any potential incompatibilities in the ChangeLog, of course)
