### ISSUE TITLE
 very long home assistant bsb-lan entities

### ISSUE THREAD

**Issue by Kacharroing12** [fredlcore/BSB-LAN#695]
I have a problem with the entities received by mqtt bsb-lan, they are too long, they are not of the type:
- platform: mqtt
    state_topic: "bsb-lan/10004"

![2024-12-17 20_38_26-Herramientas para desarrolladores – Home Assistant - Escuela_ Microsoft​ Edge](https://github.com/user-attachments/assets/71a487b7-2436-43d9-9ab6-8f797fa83a5e)

and there are 1015 entities of that type

![2024-12-17 20_44_22-Ajustes – Home Assistant - Escuela_ Microsoft​ Edge](https://github.com/user-attachments/assets/4bd746fb-50cd-41c2-aa34-90abf335dcc1)

help me

**Comment by fredlcore** [comment]
If this is a bug report, then use the template for a bug report and provide _all_ the information that is requested there. Otherwise there is no way to help you.
